sudo: false
language: node_js
cache: yarn
node_js:
  - '9'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run flow
  - yarn run lint
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
