sudo: false
language: node_js
cache: yarn
node_js:
  - 'stable'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run flow -- check
  - yarn run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
