version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/component-docs

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/component-docs
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: |
          yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint-and-flow:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/component-docs
        - run: |
            yarn lint
            yarn flow
  build-package:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/component-docs
        - run: yarn prepare

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build-package:
          requires:
            - install-dependencies
